/* ═══════════════════════════════════════════════════════════
   学术源流数据层
   —— 与呈现层解耦。工作流核查完成后在此合并扩充。
   confidence: 1=已逐条核准  0=待核
   ═══════════════════════════════════════════════════════════ */

const SCHOOLS = [
  { id:'classical',    name:'古典源流',        sub:'机器、工厂与劳动',       span:[1832,1936], c:'#3B4A7A', cd:'#8FA0C6' },
  { id:'cybernetics',  name:'控制论与自动化',  sub:'共生还是替代',           span:[1948,1985], c:'#3E5C7E', cd:'#89AAC8' },
  { id:'humanfactors', name:'人因工程',        sub:'警觉、自满与讽刺',       span:[1948,2020], c:'#3F6E76', cd:'#7FB8C0' },
  { id:'casa',         name:'拟人化与 CASA',   sub:'计算机作为社会行动者',   span:[1966,2026], c:'#4E7A64', cd:'#88C0A2' },
  { id:'digitallabor', name:'数字劳动',        sub:'人被算法管',             span:[1983,2026], c:'#7A7A4A', cd:'#C0C084' },
  { id:'responsibility',name:'责任与伦理',     sub:'真空、溃缩区、主人',     span:[1980,2026], c:'#8A6B3A', cd:'#D0AC72' },
  { id:'teaming',      name:'AI 作为队友',     sub:'团队科学的介入',         span:[2018,2026], c:'#8A5236', cd:'#CE9070' },
  { id:'llm',          name:'LLM 实证',        sub:'2023 年之后',            span:[2023,2026], c:'#8A3B44', cd:'#CE7C86' },
  { id:'chinese',      name:'中文学界',        sub:'平行轨道',               span:[2015,2026], c:'#6B3B62', cd:'#B27FA8' },
];

/* design: rct | field | quasi | cross | retro | survey | meta | theory | case
   peer:   1 已同行评议  0 预印本/工作论文/报告 */
const WORKS = [
  /* ── 古典源流 ─────────────────────────────────────── */
  { id:'babbage1832', y:1832, s:'classical', a:'Babbage, C.',
    t:'On the Economy of Machinery and Manufactures', zh:'论机器与制造业的经济',
    v:'Charles Knight', k:'把劳动分工推进到"按技能分派工序以压低工资"，即巴贝奇原则。',
    r:'最早把"拆解任务以便廉价执行"讲成经济学，与今天把工作拆成提示词同构。', conf:1 },
  { id:'ure1835', y:1835, s:'classical', a:'Ure, A.',
    t:'The Philosophy of Manufactures', zh:'制造业的哲学',
    v:'Charles Knight', k:'为工厂制辩护，明确把机器称作驯服工人不驯的手段。',
    r:'"机器作为纪律工具"的最早直白表述；与马克思读的是同一批事实。', conf:1 },
  { id:'marx1858', y:1858, s:'classical', a:'Marx, K.',
    t:'Grundrisse（Fragment on Machines）', zh:'政治经济学批判大纲·机器论片断',
    v:'手稿，1939 年首次刊行', k:'活劳动被并入死劳动，工人成为机器体系的有意识肢体。',
    r:'"谁支配谁"这一问的源头。今天的指挥关系是它的镜像。', conf:1 },
  { id:'marx1867', y:1867, s:'classical', a:'Marx, K.',
    t:'Das Kapital, Bd. I, Kap. 13「Maschinerie und große Industrie」', zh:'资本论·第一卷·机器和大工业',
    v:'Otto Meissner', k:'系统论证机器如何重组劳动过程与劳动力价值。',
    r:'去技能化命题的最早完整版本，早于布雷弗曼一百年。', conf:1 },
  { id:'taylor1911', y:1911, s:'classical', a:'Taylor, F. W.',
    t:'The Principles of Scientific Management', zh:'科学管理原理',
    v:'Harper & Brothers', k:'把"想怎么干"从工人手里移交给计划部门。',
    r:'构思与执行的分离。今天的问题是使用者搞错了自己站哪一端。', conf:1 },
  { id:'buttrick1952', y:1952, s:'classical', a:'Buttrick, J.',
    t:'The Inside Contract System', zh:'内部承包制',
    v:'The Journal of Economic History 12(3)', k:'考据十九世纪工厂把车间整体包给工头的制度。',
    r:'"工头"这个位置的史学原型：有支配权，无所有权，行情一变先被踢开。', conf:1 },
  { id:'jacoby1985', y:1985, s:'classical', a:'Jacoby, S. M.',
    t:'Employing Bureaucracy', zh:'雇佣科层制',
    v:'Columbia University Press', k:'描述美国工厂"工头帝国"如何被人事科层取代。',
    r:'说明支配权下放给底层是一种制度设计，不是自然状态。', conf:1 },
  { id:'xiayan1936', y:1936, s:'classical', a:'夏衍',
    t:'包身工', zh:'包身工',
    v:'《光明》创刊号', k:'中国近代带工制的报告文学记录。',
    r:'中文语境里"把头/拿摩温"的一手史料，与内包工制同构。', conf:1 },

  /* ── 控制论与自动化 ───────────────────────────────── */
  { id:'wiener1950', y:1950, s:'cybernetics', a:'Wiener, N.',
    t:'The Human Use of Human Beings', zh:'人有人的用处',
    v:'Houghton Mifflin', k:'控制论奠基者对自动化取代人的早期警告。',
    r:'最早提出"把人当机器用"的伦理问题，书名本身就是论点。', conf:1 },
  { id:'licklider1960', y:1960, s:'cybernetics', a:'Licklider, J. C. R.',
    t:'Man-Computer Symbiosis', zh:'人机共生',
    v:'IRE Transactions on Human Factors in Electronics HFE-1', k:'提出人与计算机作为共生伙伴而非主仆。',
    r:'"共生"隐喻的源头。它与"AI 员工"是两条完全不同的路。', conf:1 },
  { id:'engelbart1962', y:1962, s:'cybernetics', a:'Engelbart, D. C.',
    t:'Augmenting Human Intellect: A Conceptual Framework', zh:'增强人类智能：一个概念框架',
    v:'SRI Summary Report AFOSR-3223', k:'技术的目标是增强人的能力，不是替代人。',
    r:'"增强"与"委派"的分野，正是今天两种用法的分野。', conf:1 },
  { id:'blauner1964', y:1964, s:'cybernetics', a:'Blauner, R.',
    t:'Alienation and Freedom', zh:'异化与自由',
    v:'University of Chicago Press', k:'异化随技术类型呈倒 U 型，连续流程工人异化反而低。',
    r:'技术与异化不是单调关系。对"AI 必然让人退化"是一记提醒。', conf:1 },
  { id:'braverman1974', y:1974, s:'cybernetics', a:'Braverman, H.',
    t:'Labor and Monopoly Capital', zh:'劳动与垄断资本',
    v:'Monthly Review Press', k:'把构思与执行的分离命名为去技能化的引擎。',
    r:'去技能化命题的现代版本，也是后续四十年争论的靶子。', conf:1 },
  { id:'weizenbaum1976', y:1976, s:'cybernetics', a:'Weizenbaum, J.',
    t:'Computer Power and Human Reason', zh:'计算机的力量与人的理性',
    v:'W. H. Freeman', k:'区分"计算机能做"与"应该交给计算机做"。',
    r:'ELIZA 效应的原始反思，"把 agent 当员工"最古老的反命题。', conf:1 },
  { id:'burawoy1979', y:1979, s:'cybernetics', a:'Burawoy, M.',
    t:'Manufacturing Consent', zh:'制造同意',
    v:'University of Chicago Press', k:'工人在赶工游戏中自愿参与，同意是被生产出来的。',
    r:'解释为什么"爽感"本身就是控制的一部分，而不是控制的对立面。', conf:1 },
  { id:'edwards1979', y:1979, s:'cybernetics', a:'Edwards, R.',
    t:'Contested Terrain', zh:'争夺的地带',
    v:'Basic Books', k:'控制的三种形态：简单控制、技术控制、科层控制。',
    r:'Kellogg 等 2020 的算法控制框架直接建在它上面。', conf:1 },
  { id:'winner1980', y:1980, s:'responsibility', a:'Winner, L.',
    t:'Do Artifacts Have Politics?', zh:'技术物有政治吗？',
    v:'Daedalus 109(1)', k:'技术设计本身内嵌权力安排。',
    r:'"隐喻是被谁造出来的"这个追问的理论依据。', conf:1 },
  { id:'noble1984', y:1984, s:'cybernetics', a:'Noble, D. F.',
    t:'Forces of Production', zh:'生产的力量',
    v:'Alfred A. Knopf', k:'数控机床的技术路线是管理层的选择，不是技术必然。',
    r:'反技术决定论。今天的"AI 员工"同样是选择，不是必然。', conf:1 },

  /* ── 人因工程 ─────────────────────────────────────── */
  { id:'mackworth1948', y:1948, s:'humanfactors', a:'Mackworth, N. H.',
    t:'The Breakdown of Vigilance during Prolonged Visual Search', zh:'长时视觉搜索中的警觉性崩溃',
    v:'Quarterly Journal of Experimental Psychology 1(1)', k:'时钟测验：低事件率监控任务下漏检率迅速上升。',
    r:'"我会把关"这句话的第一个反证，七十多年前就有了。', conf:1, design:'rct', peer:1 },
  { id:'sheridan1978', y:1978, s:'humanfactors', a:'Sheridan, T. B. & Verplank, W. L.',
    t:'Human and Computer Control of Undersea Teleoperators', zh:'水下遥操作的人机控制',
    v:'MIT Man-Machine Systems Laboratory', k:'提出自动化层级(levels of automation)十级量表。',
    r:'"监督控制"就是"人当主管"的工程学版本，比隐喻早四十年。', conf:1 },
  { id:'bainbridge1983', y:1983, s:'humanfactors', a:'Bainbridge, L.',
    t:'Ironies of Automation', zh:'自动化的讽刺',
    v:'Automatica 19(6):775–779', k:'自动化拿走常规活，把最难的异常留给最生疏的人。',
    r:'整个讨论的祖师爷文本。五页纸，至今没有被推翻。', conf:1 },
  { id:'perrow1984', y:1984, s:'humanfactors', a:'Perrow, C.',
    t:'Normal Accidents', zh:'正常事故',
    v:'Basic Books', k:'紧耦合复杂系统中，事故是系统属性而非人为失误。',
    r:'把追责从操作员移向系统设计，与道德溃缩区一脉相承。', conf:1 },
  { id:'norman1990', y:1990, s:'humanfactors', a:'Norman, D. A.',
    t:"The 'problem' with automation: inappropriate feedback and interaction, not over-automation", zh:'自动化的"问题"：反馈与交互不当，而非过度自动化',
    v:'Philosophical Transactions of the Royal Society B 327', k:'技能退化的根源在反馈设计，不在自动化程度本身。',
    r:'对 Bainbridge 悲观论的正面反驳，这场争论至今没有定论。', conf:1 },
  { id:'endsley1995', y:1995, s:'humanfactors', a:'Endsley, M. R. & Kiris, E. O.',
    t:'The Out-of-the-Loop Performance Problem and Level of Control in Automation', zh:'脱环绩效问题与自动化控制层级',
    v:'Human Factors 37(2)', k:'自动化程度越高，被迫接管时态势感知越低、反应越慢。',
    r:'"平时不干活，出事要你扛"的量化版本。', conf:1, design:'rct', peer:1 },
  { id:'parasuraman1997', y:1997, s:'humanfactors', a:'Parasuraman, R. & Riley, V.',
    t:'Humans and Automation: Use, Misuse, Disuse, Abuse', zh:'人与自动化：使用、误用、弃用、滥用',
    v:'Human Factors 39(2):230–253', k:'四分法。abuse 一栏指向部署自动化的组织而非操作员。',
    r:'把矛头从"你不够警觉"转向"谁这样部署的"。', conf:1 },
  { id:'skitka1999', y:1999, s:'humanfactors', a:'Skitka, L. J., Mosier, K. L. & Burdick, M.',
    t:'Does automation bias decision-making?', zh:'自动化会导致决策偏差吗？',
    v:'International Journal of Human-Computer Studies 51(5)', k:'自动化在场时出现大量遗漏错误：机器没报警的地方人也不看。',
    r:'解释了为什么"AI 没提醒我"会成为真实的失效模式。', conf:1, design:'rct', peer:1 },
  { id:'lee2004', y:2004, s:'humanfactors', a:'Lee, J. D. & See, K. A.',
    t:'Trust in Automation: Designing for Appropriate Reliance', zh:'对自动化的信任：为恰当依赖而设计',
    v:'Human Factors 46(1)', k:'信任需要与系统实际能力校准，过度与不足同样有害。',
    r:'"该不该信这个下属"的工程学版本，直击锯齿状能力边界。', conf:1 },
  { id:'parasuraman2010', y:2010, s:'humanfactors', a:'Parasuraman, R. & Manzey, D. H.',
    t:'Complacency and Bias in Human Use of Automation', zh:'人使用自动化中的自满与偏差',
    v:'Human Factors 52(3)', k:'自动化越可靠，人的抽查频率掉得越快，且毫无自觉。',
    r:'"我会审"这句承诺的失效机制，而且当事人察觉不到。', conf:1, design:'meta', peer:1 },

  /* ── 拟人化与 CASA ────────────────────────────────── */
  { id:'weizenbaum1966', y:1966, s:'casa', a:'Weizenbaum, J.',
    t:'ELIZA—A Computer Program For the Study of Natural Language Communication', zh:'ELIZA：一个研究自然语言交流的计算机程序',
    v:'Communications of the ACM 9(1)', k:'一个几百行的程序就让人产生情感依附。',
    r:'ELIZA 效应：拟人化不需要智能，只需要一点对话形式。', conf:1 },
  { id:'dennett1987', y:1987, s:'casa', a:'Dennett, D. C.',
    t:'The Intentional Stance', zh:'意向立场',
    v:'MIT Press', k:'把系统当作有意图的行动者来预测，是一种合法且高效的策略。',
    r:'为"把 AI 当员工"提供了最强的哲学辩护，必须正面处理。', conf:1 },
  { id:'suchman1987', y:1987, s:'casa', a:'Suchman, L. A.',
    t:'Plans and Situated Actions', zh:'计划与情境行动',
    v:'Cambridge University Press', k:'人的行动是情境性的，计划是事后叙述而非行动的原因。',
    r:'对"它决定去做 X"这种读法的根本性批评，直接适用于 agent。', conf:1 },
  { id:'latour1992', y:1992, s:'casa', a:'Latour, B.',
    t:'Where Are the Missing Masses? The Sociology of a Few Mundane Artifacts', zh:'缺失的大众在哪里？几件平凡技术物的社会学',
    v:'in Shaping Technology/Building Society, MIT Press', k:'把行动能力分配给非人行动者。',
    r:'"AI 算不算行动者"这个问题的理论框架来源。', conf:1 },
  { id:'nass1994', y:1994, s:'casa', a:'Nass, C., Steuer, J. & Tauber, E. R.',
    t:'Computers Are Social Actors', zh:'计算机是社会行动者',
    v:'CHI 1994', k:'人会不自觉地对计算机套用社交规则，且压不住。',
    r:'CASA 范式奠基。它说明"当员工"不是文化选择，是认知默认。', conf:1, design:'rct', peer:1 },
  { id:'nassmoon2000', y:2000, s:'casa', a:'Nass, C. & Moon, Y.',
    t:'Machines and Mindlessness: Social Responses to Computers', zh:'机器与无心：对计算机的社会性反应',
    v:'Journal of Social Issues 56(1)', k:'社交反应是无意识的，明知是机器也照样发生。',
    r:'"我知道它没感觉"这句自我安慰不构成任何保护。', conf:1 },
  { id:'epley2007', y:2007, s:'casa', a:'Epley, N., Waytz, A. & Cacioppo, J. T.',
    t:'On Seeing Human: A Three-Factor Theory of Anthropomorphism', zh:'看见人：拟人化的三因素理论',
    v:'Psychological Review 114(4)', k:'拟人化由知识可及性、效能动机、社交动机三者驱动。',
    r:'预测了谁最容易把 AI 当人：越孤立、越想掌控的人越容易。', conf:1 },
  { id:'turkle2011', y:2011, s:'casa', a:'Turkle, S.',
    t:'Alone Together', zh:'群体性孤独',
    v:'Basic Books', k:'我们对技术的要求越来越多，对彼此的要求越来越少。',
    r:'民族志研究而非实验证据，引用时须标明。', conf:1, design:'case', peer:1 },
  { id:'bender2021', y:2021, s:'casa', a:'Bender, E. M., Gebru, T., McMillan-Major, A. & Shmitchell, S.',
    t:'On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?', zh:'论随机鹦鹉的危险：语言模型会太大吗？',
    v:'FAccT 2021', k:'人倾向于在本无意义处赋予意义，制造理解的幻觉。',
    r:'"把 agent 当员工"的认知机制原型。', conf:1 },
  { id:'bartneck2020', y:2020, s:'casa', a:'Bartneck, C. & Keijsers, M.',
    t:'The morality of abusing a robot', zh:'虐待机器人的道德性',
    v:'Paladyn, Journal of Behavioral Robotics 11(1)', k:'预测攻击行为的是去心智化，不是拟人化。',
    r:'把"对 AI 粗鲁会不会变坏"这个问题整个翻了过来。', conf:1, design:'rct', peer:1 },
  { id:'shanahan2024', y:2024, s:'casa', a:'Shanahan, M.',
    t:'Talking About Large Language Models', zh:'谈论大语言模型',
    v:'Communications of the ACM 67(2)', k:'日常口语可以拟人化，涉及能力判断时必须切换语言。',
    r:'给出了一条可操作的分界线，不是全盘否定隐喻。', conf:1 },
  { id:'marchegiani2025', y:2025, s:'casa', a:'Marchegiani, B.',
    t:'Anthropomorphism, False Beliefs, and Conversational AIs', zh:'拟人化、错误信念与对话式人工智能',
    v:'Journal of Applied Philosophy 42(5)', k:'拟人化本身即为恶：它让人套用错误的行为规范。',
    r:'把"信任一个同事"的规范套到统计模型上，损害的是自主性。', conf:1 },

  /* ── 数字劳动 ─────────────────────────────────────── */
  { id:'hochschild1983', y:1983, s:'digitallabor', a:'Hochschild, A. R.',
    t:'The Managed Heart', zh:'心灵的整饰',
    v:'University of California Press', k:'情感劳动：把情绪表达变成被雇佣的工作内容。',
    r:'理解"AI 谄媚"与"讨好型人格"的关键前史。', conf:1 },
  { id:'zuboff1988', y:1988, s:'digitallabor', a:'Zuboff, S.',
    t:'In the Age of the Smart Machine', zh:'智能机器时代',
    v:'Basic Books', k:'automate 与 informate 的二分：同一技术可夺权也可赋权。',
    r:'技术效果取决于权力配置而非技术本身，四十年前就讲透了。', conf:1 },
  { id:'terranova2000', y:2000, s:'digitallabor', a:'Terranova, T.',
    t:'Free Labor: Producing Culture for the Digital Economy', zh:'免费劳动：为数字经济生产文化',
    v:'Social Text 18(2)', k:'网络上的无偿参与也是被榨取的劳动。',
    r:'"你写提示词等于交出私产"这一判断的理论前身。', conf:1 },
  { id:'autor2003', y:2003, s:'digitallabor', a:'Autor, D. H., Levy, F. & Murnane, R. J.',
    t:'The Skill Content of Recent Technological Change', zh:'近期技术变迁的技能构成',
    v:'Quarterly Journal of Economics 118(4)', k:'任务模型：能被明确规则描述的任务先被自动化。',
    r:'注意：就业极化的经验证据来自后续研究，不要归给这一篇。', conf:1 },
  { id:'autor2014', y:2014, s:'digitallabor', a:'Autor, D. H.',
    t:"Polanyi's Paradox and the Shape of Employment Growth", zh:'波兰尼悖论与就业增长的形态',
    v:'NBER Working Paper 20485', k:'机器学不会人说不出口的默会知识。',
    r:'今天这道门槛被"人自愿把默会知识写成提示词"绕开了。', conf:1, peer:0 },
  { id:'lee2015', y:2015, s:'digitallabor', a:'Lee, M. K., Kusbit, D., Metsky, E. & Dabbish, L.',
    t:'Working with Machines: The Impact of Algorithmic and Data-Driven Management on Human Workers', zh:'与机器共事：算法与数据驱动管理对劳动者的影响',
    v:'CHI 2015', k:'算法作为管理者的最早实证研究之一。',
    r:'"人被算法管"这条线的起点，与本议题恰好相反。', conf:1, design:'field', peer:1 },
  { id:'rosenblat2018', y:2018, s:'digitallabor', a:'Rosenblat, A.',
    t:'Uberland', zh:'优步之国',
    v:'University of California Press', k:'平台反复告诉司机"你是自己的老板"，自主感升、议价权降。',
    r:'"当老板的感觉"和"当老板"之间隔着一整套制度。', conf:1, design:'case', peer:1 },
  { id:'graysuri2019', y:2019, s:'digitallabor', a:'Gray, M. L. & Suri, S.',
    t:'Ghost Work', zh:'销声匿迹',
    v:'Houghton Mifflin Harcourt', k:'自动化背后大量隐藏的人力劳动。',
    r:'"AI 员工"话语系统性掩盖了背后真实的人。', conf:1 },
  { id:'kellogg2020', y:2020, s:'digitallabor', a:'Kellogg, K. C., Valentine, M. A. & Christin, A.',
    t:'Algorithms at Work: The New Contested Terrain of Control', zh:'工作中的算法：控制的新争夺地带',
    v:'Academy of Management Annals 14(1):366–410', k:'算法控制的 6R 框架：指挥、评估、惩戒各两项。',
    r:'管理权限正被上移到平台，而不是下放给每个员工。', conf:1 },
  { id:'acemoglu2023', y:2023, s:'digitallabor', a:'Acemoglu, D. & Johnson, S.',
    t:'Power and Progress', zh:'权力与进步',
    v:'PublicAffairs', k:'so-so automation：只比人略强的技术削弱劳动者议价能力。',
    r:'解释了为什么提效不等于加薪，反而可能是裁员的论据。', conf:1 },

  /* ── 责任与伦理 ───────────────────────────────────── */
  { id:'nissenbaum1996', y:1996, s:'responsibility', a:'Nissenbaum, H.',
    t:'Accountability in a Computerized Society', zh:'计算机化社会中的问责',
    v:'Science and Engineering Ethics 2(1)', k:'多手问题：参与者众多导致无人可被追责。',
    r:'责任稀释的最早系统论述，早于学习型系统的出现。', conf:1 },
  { id:'matthias2004', y:2004, s:'responsibility', a:'Matthias, A.',
    t:'The responsibility gap: Ascribing responsibility for the actions of learning automata', zh:'责任真空：为学习型机器的行为归责',
    v:'Ethics and Information Technology 6(3):175–183', k:'当机器基于学习行动，传统责任链条断裂。',
    r:'"责任真空"一词的出处。今天被大量误用，需要回到原文。', conf:1 },
  { id:'sparrow2007', y:2007, s:'responsibility', a:'Sparrow, R.',
    t:'Killer Robots', zh:'杀人机器人',
    v:'Journal of Applied Philosophy 24(1)', k:'自主武器的责任真空：既不能追责机器也不能追责指挥官。',
    r:'把责任真空推到极端场景，检验它是否成立。', conf:1 },
  { id:'coeckelbergh2015', y:2015, s:'responsibility', a:'Coeckelbergh, M.',
    t:'The tragedy of the master: automation, vulnerability, and distance', zh:'主人的悲剧：自动化、脆弱性与距离',
    v:'Ethics and Information Technology 17(3):219–229', k:'真正的问题不是人被奴役，而是人仍然是主人。',
    r:'本综述的哲学枢纽。写在大模型出现的七年前。', conf:1, pivot:1 },
  { id:'elish2019', y:2019, s:'responsibility', a:'Elish, M. C.',
    t:'Moral Crumple Zones: Cautionary Tales in Human-Robot Interaction', zh:'道德溃缩区：人机交互的警世故事',
    v:'Engaging Science, Technology, and Society 5:40–60', k:'处在人机交界处的操作员吸收责任、保护系统。',
    r:'对"人类自居老板"最致命的一条批评：你同时被指定为溃缩区。', conf:1, pivot:1 },
  { id:'santonidesio2021', y:2021, s:'responsibility', a:'Santoni de Sio, F. & Mecacci, G.',
    t:'Four Responsibility Gaps with Artificial Intelligence', zh:'人工智能的四类责任真空',
    v:'Philosophy & Technology 34', k:'把责任真空拆成文化、道德、公共、能动四类。',
    r:'笼统谈"责任真空"已经不够，要问是哪一类。', conf:1 },
  { id:'tigard2021', y:2021, s:'responsibility', a:'Tigard, D. W.',
    t:'There Is No Techno-Responsibility Gap', zh:'不存在技术责任真空',
    v:'Philosophy & Technology 34', k:'正面反驳：现有责任概念足以覆盖 AI 场景。',
    r:'必须与 Matthias 并读，否则就是一面之词。', conf:1 },
  { id:'kolt2025', y:2025, s:'responsibility', a:'Kolt, N.',
    t:'Governing AI Agents', zh:'治理人工智能代理',
    v:'Notre Dame Law Review 101 (forthcoming); arXiv:2501.07913', k:'该借用的是委托—代理理论与代理法，不是 HR 话语。',
    r:'"如果非要用雇佣隐喻，法理上会遇到什么"的严谨对照组。', conf:1, peer:0 },

  /* ── AI 作为队友 ──────────────────────────────────── */
  { id:'seeber2020', y:2020, s:'teaming', a:'Seeber, I. et al.',
    t:'Machines as teammates: A research agenda on AI in team collaboration', zh:'机器作为队友：团队协作中人工智能的研究议程',
    v:'Information & Management 57(2)', k:'多作者研究议程，正面提出把 AI 当队友。',
    r:'学界正面处理这个隐喻的少数文献之一。', conf:1 },
  { id:'vaccaro2024', y:2024, s:'teaming', a:'Vaccaro, M., Almaatouq, A. & Malone, T.',
    t:'When combinations of humans and AI are useful: A systematic review and meta-analysis', zh:'人机组合何时有用：系统综述与元分析',
    v:'Nature Human Behaviour 8', k:'元分析结论对"人机组合必然更强"是否定性的。',
    r:'对乐观叙事最有力的一击，且是元分析级别的证据。', conf:1, design:'meta', peer:1 },

  /* ── LLM 实证 ─────────────────────────────────────── */
  { id:'dellacqua2022', y:2022, s:'llm', a:"Dell'Acqua, F.",
    t:'Falling Asleep at the Wheel: Human/AI Collaboration in a Field Experiment on HR Recruiters', zh:'在方向盘上睡着：招聘人员人机协作田野实验',
    v:'HBS Working Paper', k:'181 名招聘人员；配 99% 准确 AI 的一组反而比配 75% 的更差。',
    r:'AI 显得太好，人就不再警觉。低质量 AI 反而保住了判断力。',
    conf:1, design:'field', n:181, peer:0 },
  { id:'noy2023', y:2023, s:'llm', a:'Noy, S. & Zhang, W.',
    t:'Experimental evidence on the productivity effects of generative artificial intelligence', zh:'生成式人工智能生产率效应的实验证据',
    v:'Science 381(6654)', k:'写作任务 RCT：速度与质量同时提升，低技能者获益更大。',
    r:'乐观侧最硬的一条证据，必须给足。',
    conf:1, design:'rct', n:453, peer:1 },
  { id:'dellacqua2023', y:2023, s:'llm', a:"Dell'Acqua, F. et al.",
    t:'Navigating the Jagged Technological Frontier', zh:'在锯齿状技术边界上航行',
    v:'HBS Working Paper 24-013', k:'758 名 BCG 顾问；边界内质量 +40%，边界外正确率低约 19 个百分点。',
    r:'能力边界是锯齿状的，用资历直觉去推断必然踩空。',
    conf:1, design:'rct', n:758, peer:0 },
  { id:'sharma2023', y:2023, s:'llm', a:'Sharma, M. et al.',
    t:'Towards Understanding Sycophancy in Language Models', zh:'理解语言模型中的谄媚',
    v:'arXiv:2310.13548 (Anthropic)', k:'RLHF 标注偏好迎合；用户表示怀疑后模型会推翻正确答案。',
    r:'AI 的赞同零成本，因此零信息量。',
    conf:1, design:'quasi', peer:0 },
  { id:'brynjolfsson2023', y:2023, s:'llm', a:'Brynjolfsson, E., Li, D. & Raymond, L.',
    t:'Generative AI at Work', zh:'工作中的生成式人工智能',
    v:'NBER Working Paper 31161', k:'客服中心；新手绩效提升显著，资深者几乎无提升。',
    r:'老手的隐性经验被摊平发给所有人，稀缺性溢价消失。',
    conf:1, design:'field', peer:0 },
  { id:'lee2025chi', y:2025, s:'llm', a:'Lee, H.-P. et al.',
    t:'The Impact of Generative AI on Critical Thinking', zh:'生成式人工智能对批判性思维的影响',
    v:'CHI 2025 (Microsoft Research)', k:'对 AI 信心越高，批判性思维越少；对自己信心越高则相反。',
    r:'注意是自报告调查，不是行为测量。',
    conf:1, design:'survey', n:319, peer:1 },
  { id:'gerlich2025', y:2025, s:'llm', a:'Gerlich, M.',
    t:'AI Tools in Society: Impacts on Cognitive Offloading and the Future of Critical Thinking', zh:'社会中的人工智能工具：认知卸载与批判性思维的未来',
    v:'Societies 15(1):6', k:'AI 使用频率与批判性思维得分显著负相关，认知卸载为中介。',
    r:'横断面相关研究，作者自承无法排除反向因果。2025 年有一次更正。',
    conf:1, design:'cross', n:666, peer:1 },
  { id:'kosmyna2025', y:2025, s:'llm', a:'Kosmyna, N. et al.',
    t:'Your Brain on ChatGPT: Accumulation of Cognitive Debt', zh:'你用 ChatGPT 时的大脑：认知债务的累积',
    v:'arXiv:2506.08872 (MIT Media Lab)', k:'LLM 组脑连接最弱；83% 无法引述自己几分钟前写的内容。',
    r:'n=54，第四轮仅 18 人。作者公开列出禁用词表，要求勿称 brain rot。另有正式 Comment 质疑方法。',
    conf:1, design:'rct', n:54, peer:0, caution:1 },
  { id:'budzyn2025', y:2025, s:'llm', a:'Budzyń, K. et al.',
    t:'Endoscopist deskilling risk after exposure to artificial intelligence in colonoscopy', zh:'结肠镜检查中接触人工智能后的内镜医师去技能化风险',
    v:'Lancet Gastroenterology & Hepatology 10(10):896–903', k:'腺瘤检出率由 28.4% 降至 22.4%。',
    r:'回顾性观察研究，非随机。同期例数由 795 涨到 1382 是重大混杂。发表后 1 次更正、3 封质疑信。',
    conf:1, design:'retro', n:1443, peer:1, caution:1 },
  { id:'brynjolfsson2025', y:2025, s:'llm', a:'Brynjolfsson, E. et al.',
    t:'Canaries in the Coal Mine? Six Facts about the Recent Employment Effects of AI', zh:'煤矿里的金丝雀？关于人工智能近期就业效应的六个事实',
    v:'Stanford Digital Economy Lab Working Paper', k:'AI 高暴露职业中 22–25 岁就业相对下降约 13%。',
    r:'新手楼梯正在被拆。结论学界仍有争议。',
    conf:1, design:'quasi', peer:0, caution:1 },
  { id:'kalai2025', y:2025, s:'llm', a:'Kalai, A. T. et al.',
    t:'Why Language Models Hallucinate', zh:'语言模型为何产生幻觉',
    v:'arXiv (OpenAI)', k:'主流评测奖励猜测、惩罚弃权，幻觉是评分机制的产物。',
    r:'解释了为什么 AI 的错误是"穿着正装的假货"而不是缺席。',
    conf:1, design:'theory', peer:0 },
  { id:'cheng2026', y:2026, s:'llm', a:'Cheng, M., Lee, C., Khadpe, P., Yu, S., Han, D. & Jurafsky, D.',
    t:'Sycophantic AI decreases prosocial intentions and promotes dependence', zh:'谄媚的人工智能降低亲社会意愿并助长依赖',
    v:'Science 391(6792)', k:'仅一次交互即降低修复人际冲突、承担责任的意愿。',
    r:'唯一被实验证实的外溢，且方向与直觉相反：不是变凶，是不愿低头。',
    conf:1, design:'rct', n:2405, peer:1, pivot:1 },
  { id:'anthropic2026', y:2026, s:'llm', a:'Anthropic',
    t:'How AI assistance impacts the formation of coding skills', zh:'人工智能辅助如何影响编程技能的形成',
    v:'Anthropic Research', k:'AI 组测验 50%，手写组 67%；组内会追问者 65%+，纯生成者低于 40%。',
    r:'决定结果的不是用不用，是怎么用。技能"形成"而非"退化"研究，未经同行评议。',
    conf:1, design:'rct', n:52, peer:0 },
  { id:'wiles2026', y:2026, s:'llm', a:'Wiles, E., Hsu, M., Bedard, J. & Kropp, M.',
    t:'Putting AI on the Org Chart: Evidence on Delegation and Oversight', zh:'把人工智能放上组织架构图：委托与监督的证据',
    v:'Working Paper (BU × BCG)', k:'只改称呼：审阅表现 −16%、少抓 18% 的错、上推 +44%、担责 −9pp。',
    r:'全部为"组织已把 AI 列上架构图"那 23% 子组的效应，全样本平均效应很小。说成人类员工时审阅最认真。',
    conf:1, design:'rct', n:813, peer:0, pivot:1, caution:1 },
  { id:'chalkidis2026', y:2026, s:'llm', a:'Chalkidis, I. & Søgaard, A.',
    t:'Brainrot: Deskilling and Addiction are Overlooked AI Risks', zh:'脑腐：去技能化与成瘾是被忽视的人工智能风险',
    v:'arXiv:2605.03512 (FAccT 2026)', k:'2025 年顶会约 18000 篇论文中仅 10 篇涉及认知与心理健康。',
    r:'回答了"为什么这类风险讨论水位这么低"：学术激励不指向那里。',
    conf:1, design:'meta', peer:1 },
];

/* 影响与反驳关系。kind: 继承 | 反驳 | 修正 | 借用 */
const LINKS = [
  { f:'ure1835',        t:'marx1858',        k:'反驳' },
  { f:'babbage1832',    t:'marx1867',        k:'继承' },
  { f:'taylor1911',     t:'braverman1974',   k:'继承' },
  { f:'marx1867',       t:'braverman1974',   k:'继承' },
  { f:'braverman1974',  t:'burawoy1979',     k:'反驳' },
  { f:'braverman1974',  t:'edwards1979',     k:'修正' },
  { f:'braverman1974',  t:'noble1984',       k:'修正' },
  { f:'buttrick1952',   t:'jacoby1985',      k:'继承' },
  { f:'bainbridge1983', t:'norman1990',      k:'反驳' },
  { f:'mackworth1948',  t:'parasuraman2010', k:'继承' },
  { f:'sheridan1978',   t:'endsley1995',     k:'继承' },
  { f:'bainbridge1983', t:'endsley1995',     k:'继承' },
  { f:'parasuraman1997',t:'lee2004',         k:'继承' },
  { f:'skitka1999',     t:'parasuraman2010', k:'继承' },
  { f:'weizenbaum1966', t:'weizenbaum1976',  k:'继承' },
  { f:'weizenbaum1966', t:'nass1994',        k:'继承' },
  { f:'nass1994',       t:'nassmoon2000',    k:'继承' },
  { f:'nass1994',       t:'epley2007',       k:'修正' },
  { f:'dennett1987',    t:'suchman1987',     k:'反驳' },
  { f:'suchman1987',    t:'bender2021',      k:'继承' },
  { f:'dennett1987',    t:'marchegiani2025', k:'反驳' },
  { f:'nass1994',       t:'bartneck2020',    k:'修正' },
  { f:'shanahan2024',   t:'marchegiani2025', k:'反驳' },
  { f:'edwards1979',    t:'kellogg2020',     k:'继承' },
  { f:'zuboff1988',     t:'kellogg2020',     k:'继承' },
  { f:'lee2015',        t:'kellogg2020',     k:'继承' },
  { f:'terranova2000',  t:'graysuri2019',    k:'继承' },
  { f:'rosenblat2018',  t:'kellogg2020',     k:'继承' },
  { f:'autor2003',      t:'autor2014',       k:'继承' },
  { f:'autor2014',      t:'acemoglu2023',    k:'继承' },
  { f:'nissenbaum1996', t:'matthias2004',    k:'继承' },
  { f:'matthias2004',   t:'sparrow2007',     k:'继承' },
  { f:'matthias2004',   t:'tigard2021',      k:'反驳' },
  { f:'matthias2004',   t:'santonidesio2021',k:'修正' },
  { f:'perrow1984',     t:'elish2019',       k:'继承' },
  { f:'winner1980',     t:'elish2019',       k:'继承' },
  { f:'matthias2004',   t:'kolt2025',        k:'修正' },
  { f:'seeber2020',     t:'vaccaro2024',     k:'反驳' },
  { f:'bainbridge1983', t:'dellacqua2022',   k:'继承' },
  { f:'parasuraman2010',t:'dellacqua2022',   k:'继承' },
  { f:'lee2004',        t:'dellacqua2023',   k:'继承' },
  { f:'sharma2023',     t:'cheng2026',       k:'继承' },
  { f:'nass1994',       t:'wiles2026',       k:'继承' },
  { f:'elish2019',      t:'wiles2026',       k:'继承' },
  { f:'braverman1974',  t:'anthropic2026',   k:'继承' },
  { f:'kosmyna2025',    t:'chalkidis2026',   k:'借用' },
];

/* 研究设计强度：用于证据矩阵排序与视觉编码 */
const DESIGN = {
  rct:    { label:'随机对照',       rank:5, note:'因果推断最强' },
  field:  { label:'田野实验',       rank:4, note:'真实场景，随机分配' },
  meta:   { label:'元分析/系统综述', rank:4, note:'汇总多项研究' },
  quasi:  { label:'准实验',         rank:3, note:'无随机分配' },
  retro:  { label:'回顾性观察',     rank:2, note:'前后对比，易有混杂' },
  cross:  { label:'横断面相关',     rank:2, note:'不能推因果' },
  survey: { label:'自报告调查',     rank:1, note:'主观感知，非行为测量' },
  case:   { label:'个案/民族志',    rank:1, note:'深度描述，不做推断' },
  theory: { label:'理论/机制分析',  rank:0, note:'非经验研究' },
};

/* 跨学派的断线：本综述的核心观察之一 */
const MISSING_LINKS = [
  { a:'digitallabor', b:'teaming',
    claim:'数字劳动学派研究"人被算法管"，团队科学研究"人管 AI"。同一枚硬币的两面，两支文献几乎不互相引用。' },
  { a:'humanfactors', b:'casa',
    claim:'人因工程算得出人盯不住机器，CASA 算得出人会把机器当人。两边都对，但没人把"因为当成了人，所以更不盯"接起来。' },
];
